# -*- coding: utf-8 -*-
"""time_series_forecasting_with_machine_learning_yt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1geVrqnYZOvH5r69AHSSwXtNQ0KZ44fQ2

# Time Series Forecasting Youtube Tutorial
## Using Machine Learning to Forecast Energy Consumption
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import xgboost as xgb
from sklearn.metrics import mean_squared_error
color_pal = sns.color_palette()
plt.style.use('fivethirtyeight')

"""## Types of Time Series Data

![](https://miro.medium.com/max/1400/1*V_RKPeIxCB9CS_2SsLyKXw.jpeg)

reference: https://engineering.99x.io/time-series-forecasting-in-machine-learning-3972f7a7a467
"""

df = pd.read_csv('C:/Users/HP/Documents/GitHub/FinalProject_biu_ds20/time_series/data/raw/PJME_hourly.csv')
df = df.set_index('Datetime')
df.index = pd.to_datetime(df.index)

df.plot(style='.',
        figsize=(15, 5),
        color=color_pal[0],
        title='PJME Energy Use in MW')
plt.show()

"""# Train / Test Split"""

train = df.loc[df.index < '01-01-2015']
test = df.loc[df.index >= '01-01-2015']

fig, ax = plt.subplots(figsize=(15, 5))
train.plot(ax=ax, label='Training Set', title='Data Train/Test Split')
test.plot(ax=ax, label='Test Set')
ax.axvline('01-01-2015', color='black', ls='--')
ax.legend(['Training Set', 'Test Set'])
plt.show()

df.loc[(df.index > '01-10-2010') & (df.index < '01-20-2010')] \
    .plot(figsize=(15, 5), title='Week Of Data')
plt.show()

"""# Feature Creation"""

def create_features(df):
    """
    Create time series features based on time series index.
    """
    df = df.copy()
    df['hour'] = df.index.hour
    df['dayofweek'] = df.index.dayofweek
    df['quarter'] = df.index.quarter
    df['month'] = df.index.month
    df['year'] = df.index.year
    df['dayofyear'] = df.index.dayofyear
    df['dayofmonth'] = df.index.day
    df['weekofyear'] = df.index.isocalendar().week
    return df

df = create_features(df)
print(df.head())

"""# Visualize our Feature / Target Relationship"""

fig, ax = plt.subplots(figsize=(10, 8))
sns.boxplot(data=df, x='hour', y='PJME_MW')
ax.set_title('MW by Hour')
plt.show()

fig, ax = plt.subplots(figsize=(10, 8))
sns.boxplot(data=df, x='month', y='PJME_MW', palette='Blues')
ax.set_title('MW by Month')
plt.show()

"""# Create our Model"""

train = create_features(train)
test = create_features(test)

FEATURES = ['dayofyear', 'hour', 'dayofweek', 'quarter', 'month', 'year']
TARGET = 'PJME_MW'

X_train = train[FEATURES]
y_train = train[TARGET]

X_test = test[FEATURES]
y_test = test[TARGET]

"""reg = xgb.XGBRegressor(
    # הניבוי ההתחלתי (ערך בסיס) לכל דגימה. המודל מתחיל מניחוש זה ומשפר אותו בכל צעד.
    base_score=0.5,

    # סוג המודל שבו משתמשים. 'gbtree' מציין שימוש במודל מבוסס עצים (Tree-based model).
    # זוהי ברירת המחדל והאפשרות הנפוצה ביותר.
    booster='gbtree',

    # מספר העצים (סבבי boosting) שהמודל יבנה. ככל שהמספר גבוה יותר, המודל מורכב יותר.
    n_estimators=1000,

    # מנגנון לעצירה מוקדמת כדי למנוע התאמת יתר (overfitting).
    # האימון ייפסק אם השגיאה על סט האימות לא תשתפר במשך 50 סבבים רצופים.
    early_stopping_rounds=50,

    # מטרת הלמידה. 'reg:linear' מגדיר שמדובר בבעיית רגרסיה.
    # (הערה: פרמטר זה נחשב למיושן ומומלץ להשתמש ב-'reg:squarederror').
    objective='reg:linear',

    # העומק המקסימלי של כל עץ. הגבלת העומק עוזרת למנוע התאמת יתר.
    max_depth=3,

    # קצב למידה. ערך נמוך המכווץ את "הצעדים" שהמודל מבצע בכל איטרציה,
    # מה שהופך את תהליך הלמידה לשמרני יותר ועוזר במניעת התאמת יתר.
    learning_rate=0.01
)
"""

reg = xgb.XGBRegressor(base_score=y_train.mean(), booster='gbtree',
                       n_estimators=1000,
                       early_stopping_rounds=50,
                       objective='reg:linear',
                       max_depth=10,
                       learning_rate=0.01)
reg.fit(X_train, y_train,
        eval_set=[(X_train, y_train), (X_test, y_test)],
        verbose=100)

"""# Feature Importance"""

fi = pd.DataFrame(data=reg.feature_importances_,
             index=reg.feature_names_in_,
             columns=['importance'])
fi.sort_values('importance').plot(kind='barh', title='Feature Importance')
plt.show()

"""# Forecast on Test"""

test['prediction'] = reg.predict(X_test)
df = df.merge(test[['prediction']], how='left', left_index=True, right_index=True)
ax = df[['PJME_MW']].plot(figsize=(15, 5))
df['prediction'].plot(ax=ax, style='.')
plt.legend(['Truth Data', 'Predictions'])
ax.set_title('Raw Dat and Prediction')
plt.show()

"""# Score (RMSE)"""

score = np.sqrt(mean_squared_error(test['PJME_MW'], test['prediction']))
print(f'RMSE Score on Test set: {score:0.2f}')

"""### R-squared Score"""

from sklearn.metrics import r2_score
r2 = r2_score(test['PJME_MW'], test['prediction'])
print(f'R-squared Score on Test set: {r2:0.2f}')

"""# Calculate Error
- Look at the worst and best predicted days
"""

test['error'] = np.abs(test[TARGET] - test['prediction'])
test['date'] = test.index.date
test.groupby(['date'])['error'].mean().sort_values(ascending=False).head(10)

"""# Next Steps
- More robust cross validation
- Add more features (weather forecast, holidays)
"""

# =====================================================================
# --- 10. חיזוי צריכה עתידית (Forecast) ---
# =====================================================================

# ניקח את התאריך האחרון בסט הנתונים המקורי
last_date = df.index.max()

# !!! שינוי: ניצור טווח תאריכים עתידי של 100 יום (במקום 90) !!!
future_dates = pd.date_range(start=last_date, periods=24 * 100, freq='H', name='Datetime')

# ניצור DataFrame עבור התאריכים העתידיים
future_df = pd.DataFrame(index=future_dates)

# נשתמש בפונקציה הקיימת כדי ליצור את התכונות הנדרשות למודל
future_df = create_features(future_df)

# נשתמש במודל המאומן כדי לחזות את הצריכה העתידית
future_df['prediction'] = reg.predict(future_df[FEATURES])

# הדפסת 5 השורות הראשונות של החיזוי
print("--- Future Consumption Forecast (First 5 hours) ---")
print(future_df['prediction'].head())
print("--------------------------------------------------")


# --- הצגת גרף של החיזוי העתידי בלבד (100 ימים) ---
fig, ax = plt.subplots(figsize=(15, 6))
future_df['prediction'].plot(ax=ax,
                             label='Future Forecast',
                             style='.',
                             title='100-Day Future Consumption Forecast')
ax.set_xlabel('Date')
ax.set_ylabel('Predicted Energy Use (MW)')
plt.legend()
plt.show()

import xgboost as xgb
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error
import numpy as np

# -------------------------
# הגדרת טווחי חיפוש
# -------------------------
param_grid = {
    "max_depth": [ 5,  10,15],
    "learning_rate": [0.01, 0.03, 0.05],
    "n_estimators": [450, 900, 1500],
    "subsample": [0.9, 0.97, 1.0],
    "colsample_bytree": [0.9, 0.95, 1.0]
}

# -------------------------
# מודל בסיס + עצירה מוקדמת
# -------------------------
model = xgb.XGBRegressor(
    booster='gbtree',
    objective='reg:squarederror',  # חשוב
    base_score=y_train.mean(),
    early_stopping_rounds=50,
    random_state=42
)

# -------------------------
# הגדרת Grid Search
# -------------------------
grid = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    scoring="neg_root_mean_squared_error",
    cv=3,
    verbose=1,
    n_jobs=-1
)

# -------------------------
# אימון
# -------------------------
grid.fit(
    X_train, y_train,
    eval_set=[(X_test, y_test)],
    verbose=False
)

# -------------------------
# תוצאות
# -------------------------
best_model = grid.best_estimator_
print("Best Parameters:", grid.best_params_)

# -------------------------
# RMSE על Train ו-Test
# -------------------------
train_pred = best_model.predict(X_train)
test_pred = best_model.predict(X_test)

rmse_train = np.sqrt(mean_squared_error(y_train, train_pred))
rmse_test = np.sqrt(mean_squared_error(y_test, test_pred))

print(f"RMSE Train: {rmse_train:.4f}")
print(f"RMSE Test : {rmse_test:.4f}")

"""# The End"""



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import xgboost as xgb
from sklearn.metrics import mean_squared_error, r2_score

# 1. טעינת הנתונים והכנתם
df = pd.read_csv('C:/Users/HP/Documents/GitHub/FinalProject_biu_ds20/time_series/data/raw/PJME_hourly.csv', index_col='Datetime')
df.index = pd.to_datetime(df.index)

# =====================================================================
# --- תוספת: יצירת תכונות "חלון צף" (Rolling Features) ---
# =====================================================================
# ניצור תכונות חדשות שמייצגות את ממוצע צריכת החשמל בחלון זמן מסוים
df['rolling_mean_5h'] = df['PJME_MW'].rolling(window=5).mean()
df['rolling_mean_12h'] = df['PJME_MW'].rolling(window=12).mean()

# נמלא את הערכים החסרים (NaN) שנוצרו בתחילת הדרך
# ffill ממלא קדימה, bfill ממלא אחורה כדי לוודא שאין ערכים חסרים
df.fillna(method='ffill', inplace=True)
df.fillna(method='bfill', inplace=True)
# =====================================================================

# 2. ויזואליזציה ראשונית של הנתונים
df['PJME_MW'].plot(style='.',
          figsize=(15, 5),
          color=sns.color_palette()[0],
          title='PJM East Energy Use in Megawatts')
plt.show()

# 3. חלוקת הנתונים לסט אימון וסט מבחן
train = df.loc[df.index < '01-01-2015']
test = df.loc[df.index >= '01-01-2015']

fig, ax = plt.subplots(figsize=(15, 5))
train['PJME_MW'].plot(ax=ax, label='Training Set', title='Data Train/Test Split')
test['PJME_MW'].plot(ax=ax, label='Test Set')
ax.axvline('01-01-2015', color='black', ls='--')
ax.legend(['Training Set', 'Test Set'])
plt.show()

# 4. פונקציה ליצירת תכונות מבוססות זמן
def create_features(df):
    """
    Create time series features based on time series index.
    """
    df = df.copy()
    df['hour'] = df.index.hour
    df['dayofweek'] = df.index.dayofweek
    df['quarter'] = df.index.quarter
    df['month'] = df.index.month
    df['year'] = df.index.year
    df['dayofyear'] = df.index.dayofyear
    return df

train = create_features(train)
test = create_features(test)
train.to_csv('train.csv')

# 5. הגדרת משתנים ותכונות למודל
# !!! עדכון: הוספנו את תכונות החלון הצף לרשימת הפיצ'רים !!!
FEATURES = [
    'hour', 'dayofweek', 'quarter', 'month', 'year', 'dayofyear',
    'rolling_mean_5h', 'rolling_mean_12h'
]
TARGET = 'PJME_MW'

# Convert the FEATURES list to a DataFrame before saving to CSV
features_df = pd.DataFrame(FEATURES, columns=['Features'])
features_df.to_csv('features.csv', index=False)

X_train = train[FEATURES]
y_train = train[TARGET]

X_test = test[FEATURES]
y_test = test[TARGET]

# 6. יצירת מודל, אימון והערכה
reg = xgb.XGBRegressor(base_score=0.5, booster='gbtree',
                       n_estimators=500,
                       early_stopping_rounds=50,
                       objective='reg:linear',
                       max_depth=5,
                       learning_rate=0.03)

reg.fit(X_train, y_train,
        eval_set=[(X_train, y_train), (X_test, y_test)],
        verbose=100)

# 7. הצגת חשיבות התכונות
fi = pd.DataFrame(data=reg.feature_importances_,
                  index=reg.feature_names_in_,
                  columns=['importance'])
fi.sort_values('importance').plot(kind='barh', title='Feature Importance')
plt.show() # כעת נראה גם את חשיבות התכונות החדשות

# 8. ביצוע חיזוי על סט המבחן
test['prediction'] = reg.predict(X_test)

# 9. השוואה ויזואלית בין החיזוי לנתונים האמיתיים
test['prediction'].plot(style='.', figsize=(15,5), title='Prediction vs Actuals')
test['PJME_MW'].plot(style='-', alpha=0.5)
plt.legend(['Prediction', 'Actual'])
plt.show()

# --- 11. חישוב והדפסת שגיאת המודל (הזזנו לסוף) ---
score = np.sqrt(mean_squared_error(test['PJME_MW'], test['prediction']))
print(f'RMSE Score on Test set: {score:0.2f}')

r2 = r2_score(test['PJME_MW'], test['prediction'])
print(f'R-squared Score on Test set: {r2:0.2f}')

# =====================================================================
# --- 10. חיזוי עתידי איטרטיבי ל-100 ימים ---
# =====================================================================

# ניקח עותק של כל הנתונים כדי לשמש כ"היסטוריה" מתעדכנת
history = df.copy()

# רשימה לאחסון תוצאות החיזוי העתידי
future_predictions = []

# הגדרת טווח התאריכים לחיזוי
last_date = history.index.max()
future_dates = pd.date_range(start=last_date + pd.Timedelta(hours=1), periods=24 * 100, freq='H')

print("Starting 100-day iterative forecast... (This may take a moment)")

# לולאה שרצה על כל שעה עתידית ומבצעת חיזוי
for current_date in future_dates:
    # --- שלב א: יצירת תכונות עבור השעה הנוכחית ---
    # יצירת DataFrame זמני עם התאריך הנוכחי בלבד
    temp_df = pd.DataFrame(index=[current_date])

    # 1. יצירת תכונות מבוססות זמן (שעה, יום בשבוע וכו')
    temp_df = create_features(temp_df)

    # 2. חישוב תכונות חלון צף על בסיס ההיסטוריה המלאה והמעודכנת
    rolling_mean_5h = history['PJME_MW'].rolling(window=5).mean().iloc[-1]
    rolling_mean_12h = history['PJME_MW'].rolling(window=12).mean().iloc[-1]

    temp_df['rolling_mean_5h'] = rolling_mean_5h
    temp_df['rolling_mean_12h'] = rolling_mean_12h

    # --- שלב ב: חיזוי ועדכון ---
    # 3. ביצוע חיזוי עבור השעה הנוכחית בלבד
    features_for_prediction = temp_df[FEATURES]
    prediction = reg.predict(features_for_prediction)[0]

    # 4. שמירת התוצאה ברשימה
    future_predictions.append(prediction)

    # 5. עדכון ההיסטוריה עם החיזוי החדש - זהו השלב הרקורסיבי
    # כדי שהחישוב של השעה הבאה ישתמש בתוצאה הנוכחית
    new_row = pd.DataFrame({'PJME_MW': [prediction]}, index=[current_date])
    history = pd.concat([history, new_row])

print("Forecast complete.")

# יצירת DataFrame סופי מכל החיזויים שביצענו
future_df = pd.DataFrame(data=future_predictions, index=future_dates, columns=['prediction'])

# --- הצגת גרף של החיזוי העתידי בלבד (100 ימים) ---
fig, ax = plt.subplots(figsize=(15, 6))
future_df['prediction'].plot(ax=ax,
                             label='Future Forecast',
                             style='.',
                             title='100-Day Future Consumption Forecast')
ax.set_xlabel('Date')
ax.set_ylabel('Predicted Energy Use (MW)')
plt.legend()
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import lightgbm as lgb
from sklearn.metrics import mean_squared_error, r2_score

# 1. טעינת הנתונים
df = pd.read_csv('C:/Users/HP/Documents/GitHub/FinalProject_biu_ds20/time_series/data/raw/PJME_hourly.csv', index_col='Datetime')
df.index = pd.to_datetime(df.index)

# יצירת תכונות חלון צף
df['rolling_mean_5h'] = df['PJME_MW'].rolling(window=5).mean()
df['rolling_mean_12h'] = df['PJME_MW'].rolling(window=12).mean()
df.fillna(method='ffill', inplace=True)
df.fillna(method='bfill', inplace=True)

# 2. ויזואליזציה
df['PJME_MW'].plot(style='.', figsize=(15,5),
                   color=sns.color_palette()[0],
                   title='PJM East Energy Use in Megawatts')
plt.show()

# 3. חלוקה ל-Train/Test
train = df.loc[df.index < '01-01-2015']
test  = df.loc[df.index >= '01-01-2015']

fig, ax = plt.subplots(figsize=(15,5))
train['PJME_MW'].plot(ax=ax, label='Training Set')
test['PJME_MW'].plot(ax=ax, label='Test Set')
ax.axvline('01-01-2015', color='black', ls='--')
ax.legend()
plt.show()

# 4. יצירת פיצ'רים מבוססי זמן
def create_features(df):
    df = df.copy()
    df['hour'] = df.index.hour
    df['dayofweek'] = df.index.dayofweek
    df['quarter'] = df.index.quarter
    df['month'] = df.index.month
    df['year'] = df.index.year
    df['dayofyear'] = df.index.dayofyear
    return df

train = create_features(train)
test = create_features(test)

FEATURES = ['hour', 'dayofweek', 'quarter', 'month', 'year', 'dayofyear',
            'rolling_mean_5h', 'rolling_mean_12h']
TARGET = 'PJME_MW'

X_train = train[FEATURES]
y_train = train[TARGET]

X_test = test[FEATURES]
y_test = test[TARGET]

# ================================================================
# 6. מודל LightGBM מקביל ל-XGBoost שלך
# ================================================================
lgb_model = lgb.LGBMRegressor(
    n_estimators=500,
    learning_rate=0.03,
    max_depth=5,
    objective='regression'
)

lgb_model.fit(
    X_train, y_train,
    eval_set=[(X_train, y_train), (X_test, y_test)],
    eval_metric='rmse',
    callbacks=[
        lgb.early_stopping(stopping_rounds=50),
        lgb.log_evaluation(period=100)
    ]
)


# 7. חשיבות תכונות
fi = pd.DataFrame({
    'feature': FEATURES,
    'importance': lgb_model.feature_importances_
})
fi.set_index('feature').sort_values('importance').plot(kind='barh',
                                                       figsize=(8,6),
                                                       title='Feature Importance - LightGBM')
plt.show()

# 8. חיזוי
test['prediction'] = lgb_model.predict(X_test)

# 9. השוואה ויזואלית
test['prediction'].plot(style='.', figsize=(15,5), title='Prediction vs Actuals')
test['PJME_MW'].plot(alpha=0.5)
plt.legend(['Prediction', 'Actual'])
plt.show()

# 10. מדדים
rmse = np.sqrt(mean_squared_error(test['PJME_MW'], test['prediction']))
r2 = r2_score(test['PJME_MW'], test['prediction'])

print(f'RMSE Score on Test set: {rmse:0.2f}')
print(f'R-squared Score on Test set: {r2:0.2f}')

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# יצירת מודל Random Forest עם ברירות מחדל בלבד
rf_model = RandomForestRegressor()

# אימון המודל
rf_model.fit(X_train, y_train)

# חיזוי
test['prediction'] = rf_model.predict(X_test)

# חשיבות מאפיינים
fi = pd.DataFrame({
    'feature': FEATURES,
    'importance': rf_model.feature_importances_
})
fi.set_index('feature').sort_values('importance').plot(kind='barh',
                                                       figsize=(8,6),
                                                       title='Feature Importance - RandomForest')
plt.show()

# השוואה חזותית בין חיזוי לנתוני אמת
test['prediction'].plot(style='.', figsize=(15,5), title='Prediction vs Actuals')
test['PJME_MW'].plot(alpha=0.5)
plt.legend(['Prediction', 'Actual'])
plt.show()

# מדדי איכות
rmse = np.sqrt(mean_squared_error(test['PJME_MW'], test['prediction']))
r2 = r2_score(test['PJME_MW'], test['prediction'])

print(f'RMSE Score on Test set: {rmse:0.2f}')
print(f'R-squared Score on Test set: {r2:0.2f}')

import numpy as np
import pandas as pd
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
import lightgbm as lgb
import matplotlib.pyplot as plt

# ---------------------------------------------------
# 1) הגדרת מודלים
# ---------------------------------------------------
models = {
    "RandomForest": RandomForestRegressor(random_state=42),
    "XGBoost": XGBRegressor(objective='reg:squarederror', random_state=42),
    "LightGBM": lgb.LGBMRegressor(random_state=42)
}

# ---------------------------------------------------
# 2) גריד אחיד ככל האפשר לכל המודלים
# ---------------------------------------------------
param_grids = {
    "RandomForest": {
        "n_estimators": [100, 200, 400],
        "max_depth": [5, 10, 20],
        "min_samples_split": [2, 5],
    },

    "XGBoost": {
        "n_estimators": [100, 200, 400],
        "max_depth": [3, 5, 8],
        "learning_rate": [0.01, 0.05, 0.1],
        "subsample": [0.8, 1.0]
    },

    "LightGBM": {
        "n_estimators": [100, 200, 400],
        "max_depth": [3, 5, 8],
        "learning_rate": [0.01, 0.05, 0.1],
        "subsample": [0.8, 1.0]
    }
}

# ---------------------------------------------------
# 3) הרצת GridSearch אחת לכל מודל
# ---------------------------------------------------
results = []

for name, model in models.items():
    print(f"\n========== Running GridSearch for {name} ==========\n")

    search = GridSearchCV(
        estimator=model,
        param_grid=param_grids[name],
        scoring="neg_root_mean_squared_error",
        cv=3,
        verbose=2,
        n_jobs=-1
    )

    search.fit(X_train, y_train)
    best_model = search.best_estimator_

    # תחזיות
    y_pred = best_model.predict(X_test)

    # מדדים
    rmse = mean_squared_error(y_test, y_pred, squared=False)
    r2 = r2_score(y_test, y_pred)

    results.append({
        "Model": name,
        "RMSE": rmse,
        "R2": r2,
        "Best Params": search.best_params_
    })

# ---------------------------------------------------
# 4) טבלת תוצאות
# ---------------------------------------------------
df_results = pd.DataFrame(results)
print("\n\n================ SUMMARY RESULTS ================\n")
print(df_results[["Model", "RMSE", "R2"]])
print("\n\n================ BEST PARAMETERS ================\n")
for r in results:
    print(f"{r['Model']} → {r['Best Params']}\n")

# ---------------------------------------------------
# 5) גרפים — השוואת RMSE ו-R2
# ---------------------------------------------------
plt.figure(figsize=(10,5))
plt.bar(df_results["Model"], df_results["RMSE"])
plt.title("RMSE Comparison")
plt.ylabel("RMSE")
plt.show()

plt.figure(figsize=(10,5))
plt.bar(df_results["Model"], df_results["R2"])
plt.title("R² Comparison")
plt.ylabel("R²")
plt.show()