# -*- coding: utf-8 -*-
"""Prophet_e_Commerce_20250323.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uVJxv4XB7R-vqn12GOIxHKlUR3RcBDdw
"""

import pandas as pd
from prophet import Prophet
import altair as alt
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, r2_score



# Read the CSV file into a DataFrame
df = pd.read_excel('C:/Users/haham/Documents/GitHub/FinalProject_biu_ds20/sale-ecomm.xls')

# Use only 'Date' and 'Sales (billion USD)' columns
df = df[['Date', 'Sales (billion USD)']]

# Rename the columns
df = df.rename(columns={'Date': 'ds', 'Sales (billion USD)': 'y'})

# Convert the column `ds` to datetime, specifying the date format
df['ds'] = pd.to_datetime(df['ds'], format='%d-%m-%Y')
#
# Instantiate and fit the Prophet model
model = Prophet(interval_width=0.95)
model.fit(df)

# Create a future dataframe for forecasting
future = model.make_future_dataframe(periods=12, freq='M')

# Generate the forecast
forecast = model.predict(future)

# Display the forecast
print(forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail().to_markdown(index=False, numalign="left", stralign="left"))


# הצגת גרף של התחזית
fig1 = model.plot(forecast)
fig2 = model.plot_components(forecast)
# Create DataFrame for plotting
plot_df = forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].melt('ds', var_name='Metric', value_name='Sales')

# Plot forecast
chart = alt.Chart(plot_df).mark_line(point=True).encode(
    x=alt.X('ds:T', title='Date'),
    y=alt.Y('Sales', title='Sales (billion USD)'),
    color='Metric',
    tooltip=['ds', 'Sales', 'Metric']
).properties(
    title='Sales Forecast'
).interactive()
chart.show()
plt.show()
import matplotlib.pyplot as plt

# # סינון נתוני התחזית בלבד (מהתאריך האחרון של הנתונים ההיסטוריים)
forecast_only = forecast[forecast['ds'] >= df['ds'].max()]
#
# # יצירת גרף
plt.figure(figsize=(20, 15))

# נתוני תחזית בלבד
plt.plot(forecast_only['ds'], forecast_only['yhat'], 'b-', label='תחזית')  # קו תחזית
plt.fill_between(forecast_only['ds'], forecast_only['yhat_lower'], forecast_only['yhat_upper'], color='blue', alpha=0.2, label='טווח אי-ודאות')  # תחום אי-ודאות

# הגדרות גרף
plt.xlabel('תאריך')
plt.ylabel('מחיר')
plt.legend()
plt.grid(False)
plt.title('תחזית מחיר (מתחילת תחזית בלבד)')
plt.show()

# חישוב מדדי ביצועים
from sklearn.metrics import mean_squared_error, r2_score

# Filter forecast to match the length of df
forecast_filtered = forecast[forecast['ds'].isin(df['ds'])]

#Now calculate the metrics using the filtered forecast data
mse = mean_squared_error(df['y'], forecast_filtered['yhat'])
r2 = r2_score(df['y'], forecast_filtered['yhat'])


# הדפסת התוצאות
print(f"R² Score: {r2:.4f}")
print(f"MSE: {mse:.4f}")


# Read the CSV file into a DataFrame
df = pd.read_excel('C:/Users/haham/Documents/GitHub/FinalProject_biu_ds20/sale-ecomm.xls')

# Use only 'Date' and 'Sales (billion USD)' columns
df = df[['Date', 'Sales (billion USD)']]

# Rename the columns
df = df.rename(columns={'Date': 'ds', 'Sales (billion USD)': 'y'})

# Convert the column `ds` to datetime, specifying the date format
df['ds'] = pd.to_datetime(df['ds'], format='%d-%m-%Y')
stdev = df['y'].std()
# Calculate cap and floor dynamically
cap = df['y'].max() + (1 * stdev)  # Cap: Max + 2 stdevs
floor = df['y'].min() - (1 * stdev)  # Floor: Min - 2 stdevs
#For Floor =0
#floor = 0
# Add cap and floor to DataFrame
df['cap'] = cap
df['floor'] = floor

# Instantiate and fit the Prophet model
model = Prophet(growth='logistic',interval_width=0.95)
model.fit(df)

# Create a future dataframe for forecasting
future = model.make_future_dataframe(periods=12, freq='M')
#Adding cap and floor to future dataframe

future['cap'] = cap
future['floor'] = floor
# Generate the forecast
forecast = model.predict(future)

# Display the forecast
print(forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail().to_markdown(index=False, numalign="left", stralign="left"))


# הצגת גרף של התחזית
fig1 = model.plot(forecast)
fig2 = model.plot_components(forecast)
# Create DataFrame for plotting
plot_df = forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].melt('ds', var_name='Metric', value_name='Sales')

# Plot forecast
chart = alt.Chart(plot_df).mark_line(point=True).encode(
     y=alt.Y('Sales', title='Sales (billion USD)'),
    color='Metric',
    tooltip=['ds', 'Sales', 'Metric']
).properties(
    title='Sales Forecast'
).interactive()

# סינון נתוני התחזית בלבד (מהתאריך האחרון של הנתונים ההיסטוריים)
forecast_only = forecast[forecast['ds'] >= df['ds'].max()]

# יצירת גרף
plt.figure(figsize=(20, 15))

# נתוני תחזית בלבד
plt.plot(forecast_only['ds'], forecast_only['yhat'], 'b-', label='תחזית')  # קו תחזית
plt.fill_between(forecast_only['ds'], forecast_only['yhat_lower'], forecast_only['yhat_upper'], color='blue', alpha=0.2, label='טווח אי-ודאות')  # תחום אי-ודאות

# הגדרות גרף
plt.xlabel('תאריך')
plt.ylabel('מחיר')
plt.legend()
plt.grid(False)
plt.title('תחזית מחיר (מתחילת תחזית בלבד)')
plt.show()

# חישוב מדדי ביצועים

# Filter forecast to match the length of df
forecast_filtered = forecast[forecast['ds'].isin(df['ds'])]

#Now calculate the metrics using the filtered forecast data
mse = mean_squared_error(df['y'], forecast_filtered['yhat'])
r2 = r2_score(df['y'], forecast_filtered['yhat'])


# הדפסת התוצאות
print(f"R² Score: {r2:.4f}")
print(f"MSE: {mse:.4f}")