# -*- coding: utf-8 -*-
"""Prophet_תרגול_ (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d1rRdy_hTOP3VWSpOjrydAHLFldKFTuo

יש לטעון את הספריה Prphet
"""

# First, uninstall and reinstall prophet with its dependencies
!pip uninstall -y prophet
!pip install prophet

"""import the file to dataframe"""



"""Defining a date as ds and y as SPY column in the prophet model"""



"""Reset Index"""



"""write code for the prophet model that will train the model with a confidence interval of 95% of the cases."""

# מאמנים על הדאטה

"""Run a 30-day forward prediction for spy based on training"""



"""Historical and future graph with y upeer & Y download & y with historical data and future forecast with different color"""



"""גרף תחזית עתדית"""



