# -*- coding: utf-8 -*-
"""והשפעת_החגים_תחזיות_עליה_עם_תחזית_עתדית_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/135airLHffqTPWpTa_l0dxWkrkuFT9Xrr
"""

!pip install altair_viewer

# נתונים יומיים
import pandas as pd
from prophet import Prophet
import altair as alt
import holidays

# Read main data from CSV
file_path = '/content/data.csv'
data = pd.read_csv(file_path)

# Rename columns as necessary
data = data.rename(columns={'TARICH_HANAKAT_MAAMAD': 'ds', 'UNIQUE_MISPAR_ZEHUT_COUNT': 'y'})

# Convert date column to datetime
data['ds'] = pd.to_datetime(data['ds'], format='%m/%d/%Y')

# Read Jewish holidays from CSV
holidays_jewish = pd.read_csv('/content/Jewish_Israeli_holidays.csv')
# Adjust column names based on the actual file structure
holidays_jewish.columns = ['date', 'holiday_name']
holidays_jewish['ds'] = pd.to_datetime(holidays_jewish['date'], format='%m/%d/%Y')
holidays_jewish['holiday'] = holidays_jewish['holiday_name']
holidays_jewish = holidays_jewish[['ds', 'holiday']]

# Create Israel holiday object
israel_holidays = holidays.Israel()

# Create DataFrame for Israeli holidays
holidays_df = pd.DataFrame(
    [(date, name) for date, name in israel_holidays.items()],
    columns=['ds', 'holiday']
)

# Combine the two holiday DataFrames
holidays_combined = pd.concat([holidays_df, holidays_jewish], ignore_index=True)

# Initialize Prophet model and add holidays
model = Prophet(holidays=holidays_combined)

# Fit the model to the daily data
model.fit(data)

# Create a forecast for 120 days ahead
future = model.make_future_dataframe(periods=120, freq='D')
forecast = model.predict(future)

# Prevent negative forecasts
forecast['yhat'] = forecast['yhat'].clip(lower=0)
forecast['yhat_lower'] = forecast['yhat_lower'].clip(lower=0)
forecast['yhat_upper'] = forecast['yhat_upper'].clip(lower=0)

# Display the forecast
print(forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail())

# Plot the forecast
fig1 = model.plot(forecast)
fig2 = model.plot_components(forecast)

# Prepare DataFrame for the plot
plot_df = forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].melt('ds', var_name='Metric', value_name='Value')

# Create the forecast plot using Altair
chart = alt.Chart(plot_df).mark_line(point=True).encode(
    x='ds:T',
    y=alt.Y('Value:Q', title='כמות'),
    color='Metric:N',
    tooltip=['ds', 'Value', 'Metric']
).properties(
    title='תחזית כמות ל-120 ימים הבאים'
).interactive()

# Save the chart
chart.save('quantity_forecast_daily_israel.json')

# תחזית 90 יום יומי
import pandas as pd
from prophet import Prophet
import altair as alt

# קריאת נתונים מקובץ CSV
file_path = '/content/data.csv'
data = pd.read_csv(file_path)

# שינוי שם העמודות - 'TARICH_HANAKAT_MAAMAD' לעמודת התאריכים ו-'UNIQUE_MISPAR_ZEHUT_COUNT' לעמודת הכמויות
data = data.rename(columns={'TARICH_HANAKAT_MAAMAD': 'ds', 'UNIQUE_MISPAR_ZEHUT_COUNT': 'y'})

# המרה של עמודת התאריך לפורמט תאריך נכון
data['ds'] = pd.to_datetime(data['ds'], format='%d/%m/%Y', errors='coerce')

# בדיקה אם יש תאריכים לא חוקיים שהומרו ל-NaT
print("תאריכים חסרים אחרי ההמרה:")
print(data[data['ds'].isna()])

# הסרת תאריכים חסרים אם יש כאלה
data = data.dropna(subset=['ds'])

# אתחול מודל Prophet
model = Prophet()

# התאמת המודל לנתונים
model.fit(data)

# יצירת תחזית ל-90 ימים קדימה
future = model.make_future_dataframe(periods=120)
forecast = model.predict(future)

# סינון התחזית ל-90 הימים הבאים בלבד
forecast_90_days = forecast[forecast['ds'] > data['ds'].max()]

# הבטחת ערכים חיוביים בעמודת החזיות
forecast_90_days['yhat'] = forecast_90_days['yhat'].clip(lower=0)
forecast_90_days['yhat_lower'] = forecast_90_days['yhat_lower'].clip(lower=0)
forecast_90_days['yhat_upper'] = forecast_90_days['yhat_upper'].clip(lower=0)

# יצירת DataFrame חדש עבור הגרף - עבור תחזית 90 הימים הבאים עם רווח בר סמך
forecast_90_df = forecast_90_days[['ds', 'yhat', 'yhat_lower', 'yhat_upper']]

# טעינת ההרחבה של Altair עבור Colab
alt.renderers.enable('colab')

# יצירת הגרף עם רווח בר סמך ועם גודל מותאם
chart = alt.Chart(forecast_90_df).mark_line(point=True).encode(
    x=alt.X('ds:T', title='תאריך', axis=alt.Axis(format='%Y-%m-%d')),
    y=alt.Y('yhat:Q', title='כמות חזויה'),
    tooltip=['ds', 'yhat', 'yhat_lower', 'yhat_upper']
).properties(
    title='תחזית כמות ל-90 הימים הבאים עם רווח בר סמך',
    width=800,
    height=400
).interactive()

# הוספת רווח בר סמך לגרף
band = alt.Chart(forecast_90_df).mark_area(opacity=0.3).encode(
    x='ds:T',
    y='yhat_lower:Q',
    y2='yhat_upper:Q'
)

# הצגת הגרף עם רווח בר סמך
chart + band



# נתונים שבועים
import pandas as pd
from prophet import Prophet
import altair as alt
import holidays

# Read main data from CSV
file_path = '/content/data.csv'
data = pd.read_csv(file_path)

# Rename columns as necessary
data = data.rename(columns={'TARICH_HANAKAT_MAAMAD': 'ds', 'UNIQUE_MISPAR_ZEHUT_COUNT': 'y'})

# Convert date column to datetime
data['ds'] = pd.to_datetime(data['ds'], format='%m/%d/%Y')

# Change date to the start of the week
data['ds'] = data['ds'].dt.to_period('W').dt.to_timestamp()

# Read Jewish holidays from CSV
holidays_jewish = pd.read_csv('/content/Jewish_Israeli_holidays.csv')
# Adjust column names based on the actual file structure
holidays_jewish.columns = ['date', 'holiday_name']
holidays_jewish['ds'] = pd.to_datetime(holidays_jewish['date'], format='%m/%d/%Y')
holidays_jewish['holiday'] = holidays_jewish['holiday_name']
holidays_jewish = holidays_jewish[['ds', 'holiday']]

# Create Israel holiday object
israel_holidays = holidays.Israel()

# Create DataFrame for Israeli holidays
holidays_df = pd.DataFrame(
    [(date, name) for date, name in israel_holidays.items()],
    columns=['ds', 'holiday']
)

# Combine the two holiday DataFrames
holidays_combined = pd.concat([holidays_df, holidays_jewish], ignore_index=True)

# Initialize Prophet model and add holidays
model = Prophet(holidays=holidays_combined)

# Fit the model to the weekly data
weekly_data = data.groupby('ds').sum().reset_index()
model.fit(weekly_data)

# Create a forecast for 25 weeks ahead
future = model.make_future_dataframe(periods=25, freq='W')
forecast = model.predict(future)

# Prevent negative forecasts
forecast['yhat'] = forecast['yhat'].clip(lower=0)
forecast['yhat_lower'] = forecast['yhat_lower'].clip(lower=0)
forecast['yhat_upper'] = forecast['yhat_upper'].clip(lower=0)

# Display the forecast
print(forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail())

# Plot the forecast
fig1 = model.plot(forecast)
fig2 = model.plot_components(forecast)

# Prepare DataFrame for the plot
plot_df = forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].melt('ds', var_name='Metric', value_name='Value')

# Create the forecast plot using Altair
chart = alt.Chart(plot_df).mark_line(point=True).encode(
    x='ds:T',
    y=alt.Y('Value:Q', title='כמות'),
    color='Metric:N',
    tooltip=['ds', 'Value', 'Metric']
).properties(
    title='תחזית כמות ל-12 שבועות הבאים'
).interactive()

# Save the chart
chart.save('quantity_forecast_weekly_israel.json')

#תחזית עתידית שבועית
import pandas as pd
from prophet import Prophet
import altair as alt

# קריאת נתונים מקובץ CSV
file_path = '/content/data.csv'
data = pd.read_csv(file_path)

# שינוי שם העמודות - 'TARICH_HANAKAT_MAAMAD' לעמודת התאריכים ו-'UNIQUE_MISPAR_ZEHUT_COUNT' לעמודת הכמויות
data = data.rename(columns={'TARICH_HANAKAT_MAAMAD': 'ds', 'UNIQUE_MISPAR_ZEHUT_COUNT': 'y'})

# המרה של עמודת התאריך לפורמט תאריך נכון
data['ds'] = pd.to_datetime(data['ds'], format='%d/%m/%Y', errors='coerce')

# בדיקה אם יש תאריכים לא חוקיים שהומרו ל-NaT
print("תאריכים חסרים אחרי ההמרה:")
print(data[data['ds'].isna()])

# הסרת תאריכים חסרים אם יש כאלה
data = data.dropna(subset=['ds'])

# שינוי התאריכים לראשית השבוע
data['ds'] = data['ds'].dt.to_period('W').dt.to_timestamp()

# קיבוץ הנתונים לפי תאריך השבוע וסיכום הכמויות
weekly_data = data.groupby('ds').sum().reset_index()

# אתחול מודל Prophet
model = Prophet()

# התאמת המודל לנתונים
model.fit(weekly_data)

# יצירת תחזית ל-25 שבועות קדימה
future = model.make_future_dataframe(periods=25, freq='W')
forecast = model.predict(future)

# הבטחת ערכים חיוביים בעמודת החזיות
forecast['yhat'] = forecast['yhat'].clip(lower=0)
forecast['yhat_lower'] = forecast['yhat_lower'].clip(lower=0)
forecast['yhat_upper'] = forecast['yhat_upper'].clip(lower=0)

# סינון התחזית עבור השבועות הבאים בלבד
forecast_weeks = forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']]

# סינון תאריכים עתידיים בלבד
last_date = weekly_data['ds'].max()
future_forecast = forecast_weeks[forecast_weeks['ds'] > last_date]

# הצגת התחזיות האחרונות
print(future_forecast.tail())

# יצירת גרף עם Altair
alt.renderers.enable('colab')

# גרף של האזור בין yhat_lower ו-yhat_upper בצבע כחול שקוף
area_chart = alt.Chart(future_forecast).mark_area(color='lightblue', opacity=0.5).encode(
    x=alt.X('ds:T', axis=alt.Axis(format='%Y-%b', title='תאריך')),  # פורמט התאריך: שנה-חודש
    y='yhat_lower:Q',
    y2='yhat_upper:Q'
)

# גרף של הקו המרכזי (yhat)
line_chart = alt.Chart(future_forecast).mark_line(point=True).encode(
    x=alt.X('ds:T', axis=alt.Axis(format='%Y-%b', title='תאריך')),  # פורמט התאריך: שנה-חודש
    y=alt.Y('yhat:Q', title='כמות'),
    tooltip=['ds', 'yhat', 'yhat_lower', 'yhat_upper']
)

# שילוב שני הגרפים (השטח והקו המרכזי)
chart = area_chart + line_chart

# הצגת הגרף
chart.properties(
    title='תחזית כמות ל-25 השבועות הבאים',
    width=800,
    height=400
).interactive()

# נתונים חודשים
import pandas as pd
from prophet import Prophet
import altair as alt
import holidays

# Read main data from CSV
file_path = '/content/data.csv'
data = pd.read_csv(file_path)

# Rename columns as necessary
data = data.rename(columns={'TARICH_HANAKAT_MAAMAD': 'ds', 'UNIQUE_MISPAR_ZEHUT_COUNT': 'y'})

# Convert date column to datetime
data['ds'] = pd.to_datetime(data['ds'], format='%m/%d/%Y')

# Change date to the start of the month
data['ds'] = data['ds'].dt.to_period('M').dt.to_timestamp()

# Read Jewish holidays from CSV
holidays_jewish = pd.read_csv('/content/Jewish_Israeli_holidays.csv')
# Adjust column names based on the actual file structure
holidays_jewish.columns = ['date', 'holiday_name']
holidays_jewish['ds'] = pd.to_datetime(holidays_jewish['date'], format='%m/%d/%Y')
holidays_jewish['holiday'] = holidays_jewish['holiday_name']
holidays_jewish = holidays_jewish[['ds', 'holiday']]

# Create Israel holiday object
israel_holidays = holidays.Israel()

# Create DataFrame for Israeli holidays
holidays_df = pd.DataFrame(
    [(date, name) for date, name in israel_holidays.items()],
    columns=['ds', 'holiday']
)

# Combine the two holiday DataFrames
holidays_combined = pd.concat([holidays_df, holidays_jewish], ignore_index=True)

# Initialize Prophet model and add holidays
model = Prophet(holidays=holidays_combined)

# Fit the model to the data
model.fit(data.groupby('ds').sum().reset_index())

# Create a forecast for 12 months ahead
future = model.make_future_dataframe(periods=12, freq='M')
forecast = model.predict(future)

# Prevent negative forecasts
forecast['yhat'] = forecast['yhat'].clip(lower=0)
forecast['yhat_lower'] = forecast['yhat_lower'].clip(lower=0)
forecast['yhat_upper'] = forecast['yhat_upper'].clip(lower=0)

# Display the forecast
print(forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail())

# Plot the forecast
fig1 = model.plot(forecast)
fig2 = model.plot_components(forecast)

# Prepare DataFrame for the plot
plot_df = forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].melt('ds', var_name='Metric', value_name='Value')

import pandas as pd
from prophet import Prophet
import altair as alt

# קריאת נתונים מקובץ CSV
file_path = '/content/data.csv'
data = pd.read_csv(file_path)

# שינוי שם העמודות - 'TARICH_HANAKAT_MAAMAD' לעמודת התאריכים ו-'UNIQUE_MISPAR_ZEHUT_COUNT' לעמודת הכמויות
data = data.rename(columns={'TARICH_HANAKAT_MAAMAD': 'ds', 'UNIQUE_MISPAR_ZEHUT_COUNT': 'y'})

# המרה של עמודת התאריך לפורמט תאריך נכון
data['ds'] = pd.to_datetime(data['ds'], format='%d/%m/%Y', errors='coerce')

# בדיקה אם יש תאריכים לא חוקיים שהומרו ל-NaT
print("תאריכים חסרים אחרי ההמרה:")
print(data[data['ds'].isna()])

# הסרת תאריכים חסרים אם יש כאלה
data = data.dropna(subset=['ds'])

# שינוי התאריכים לראשית החודש
data['ds'] = data['ds'].dt.to_period('M').dt.to_timestamp()

# קיבוץ הנתונים לפי חודש וסיכום הכמויות
monthly_data = data.groupby('ds').sum().reset_index()

# אתחול מודל Prophet
model = Prophet()

# התאמת המודל לנתונים
model.fit(monthly_data)

# יצירת תחזית ל-12 חודשים קדימה
future = model.make_future_dataframe(periods=12, freq='M')
forecast = model.predict(future)

# הבטחת ערכים חיוביים בעמודת החזיות
forecast['yhat'] = forecast['yhat'].clip(lower=0)
forecast['yhat_lower'] = forecast['yhat_lower'].clip(lower=0)
forecast['yhat_upper'] = forecast['yhat_upper'].clip(lower=0)

# סינון התחזית עבור החודשים הבאים בלבד
forecast_months = forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']]

# סינון תאריכים עתידיים בלבד
last_date = monthly_data['ds'].max()
future_forecast = forecast_months[forecast_months['ds'] > last_date]

# הצגת התחזיות האחרונות
print(future_forecast.tail())

# יצירת גרף עם Altair
alt.renderers.enable('colab')

# גרף של האזור בין yhat_lower ו-yhat_upper בצבע כחול שקוף
area_chart = alt.Chart(future_forecast).mark_area(color='lightblue', opacity=0.5).encode(
    x=alt.X('ds:T', axis=alt.Axis(format='%Y-%b', title='תאריך')),  # פורמט התאריך: שנה-חודש
    y='yhat_lower:Q',
    y2='yhat_upper:Q'
)

# גרף של הקו המרכזי (yhat)
line_chart = alt.Chart(future_forecast).mark_line(point=True).encode(
    x=alt.X('ds:T', axis=alt.Axis(format='%Y-%b', title='תאריך')),  # פורמט התאריך: שנה-חודש
    y=alt.Y('yhat:Q', title='כמות'),
    tooltip=['ds', 'yhat', 'yhat_lower', 'yhat_upper']
)

# שילוב שני הגרפים (השטח והקו המרכזי)
chart = area_chart + line_chart

# הצגת הגרף
chart.properties(
    title='תחזית כמות ל-12 החודשים הבאים',
    width=800,
    height=400
).interactive()